baseurl = "/"
disqusShortname = ""
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "cn-zh"
preserveTaxonomyNames = true
theme = "ivy"
title = "艾逗笔"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "首页"
url = "/"
weight = 1
[[menu.main]]
name = "关于"
url = "/about/"
weight = 6
[[menu.main]]
name = "分类"
url = "/categories/"
weight = 3
[[menu.main]]
name = "标签"
url = "/tags/"
weight = 4
[[menu.main]]
name = "作品"
url = "/works/"
weight = 5

[params]
description = "有逻辑的脑子万里挑一。"
footer = "&copy; [艾逗笔](https://idoubi.cc) 2020 | [Github](https://github.com/idoubi)"
mpqrcode = "http://blogcdn.idoustudio.com/idoubi-mp.jpeg"

highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
highlightjsVersion = "9.12.0"

[params.comment]
repo = "idoubi/idoubi.cc"
theme = "github-light"
